#:schema node_modules/wrangler/config-schema.json
name = "workers-dbms"
main = "src/index.ts"
compatibility_date = "2024-09-09"
compatibility_flags = ["experimental"]
workers_dev = true
account_id = "0d37909e38d3e99c29fa2cd343ac421a"

[[durable_objects.bindings]]
name = "DBSM_DO"
class_name = "DBMSDO"

#[[migrations]]
#tag = "v1"
#new_sqlite_classes = ["DBMSDO"]

[build]
command = "node src/forms/templates/precompile.mjs templates src/forms/precompiled.mjs"
cwd = "."
watch_dir = "templates"


[observability]
enabled = true
