#:schema node_modules/wrangler/config-schema.json
# This is a development only wrangler.toml, for production use the one in example/wrangler.toml

name = "workers-dbms-development"
main = "src/development.ts"
compatibility_date = "2024-09-28"
workers_dev = true
account_id = "0983f9c21d0167d8d677be145016932e"

[[durable_objects.bindings]]
name = "DBSM_DO"
class_name = "DBMSDO"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["DBMSDO"]

[build]
command = "npm run build-templates"
cwd = "."
watch_dir = "templates"

[observability]
enabled = true
